[package]
name = "p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
m = { path = "/home/andrew/andrew/development/rusty/practice/practice/csv_parser/m", version = "0.1.0" }
